services:
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - services/auth-service/.env
    environment:
      DATABASE_URL: postgres://smart_campus:smart_campus_dev_password@host.docker.internal:5432/smart_campus?schema=auth_service

  student-service:
    build:
      context: .
      dockerfile: services/student-service/Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - services/student-service/.env
    environment:
      DATABASE_URL: postgres://smart_campus:smart_campus_dev_password@host.docker.internal:5432/smart_campus?schema=student_service

  course-service:
    build:
      context: .
      dockerfile: services/course-service/Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - services/course-service/.env
    environment:
      DATABASE_URL: postgres://smart_campus:smart_campus_dev_password@host.docker.internal:5432/smart_campus?schema=course_service

  attendance-service:
    build:
      context: .
      dockerfile: services/attendance-service/Dockerfile
    ports:
      - "3004:3004"
    env_file:
      - services/attendance-service/.env
    environment:
      DATABASE_URL: postgres://smart_campus:smart_campus_dev_password@host.docker.internal:5432/smart_campus?schema=attendance_service
      RABBITMQ_URL: amqp://guest:guest@host.docker.internal:5672

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - services/notification-service/.env
    environment:
      DATABASE_URL: postgres://smart_campus:smart_campus_dev_password@host.docker.internal:5432/smart_campus?schema=notification_service
      RABBITMQ_URL: amqp://guest:guest@host.docker.internal:5672

  analytics-service:
    build:
      context: .
      dockerfile: services/analytics-service/Dockerfile
    ports:
      - "3006:3006"
    env_file:
      - services/analytics-service/.env
    environment:
      DATABASE_URL: postgres://smart_campus:smart_campus_dev_password@host.docker.internal:5432/smart_campus?schema=analytics_service
      RABBITMQ_URL: amqp://guest:guest@host.docker.internal:5672

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - services/api-gateway/.env
    environment:
      AUTH_SERVICE_URL: http://auth-service:3001
      STUDENT_SERVICE_URL: http://student-service:3002
      COURSE_SERVICE_URL: http://course-service:3003
      ATTENDANCE_SERVICE_URL: http://attendance-service:3004
    depends_on:
      - auth-service
      - student-service
      - course-service
      - attendance-service