apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "dev-only-secret-change-this-in-real-deployment"
  AUTH_DATABASE_URL: "postgres://smart_campus:smart_campus_dev_password@postgres:5432/smart_campus?schema=auth_service"